---
- name: Auditbeat main configuration file transfer
  template:
    src: '{{ item }}.j2'
    dest: '/etc/auditbeat/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop:
    - 'auditbeat.yml'
    - 'auditbeat-template.json'
  register: beats_config
