---
- name: Auditbeat main configuration file transfer
  template:
    src: '{{ item }}.j2'
    dest: '/etc/auditbeat/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop:
    - 'auditbeat.yml'
    - 'auditbeat-template.json'
  register: beats_config

- name: Auditbeat systemd configuration
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/auditbeat.service'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: '\[Service\]'
  with_items:
    - { regexp: '^Restart',      line: 'Restart=on-failure' }
    - { regexp: '^RestartSec',   line: 'RestartSec=30s' }
