---
- name: Filebeat main configuration file transfer
  template:
    src: '{{ filebeat_configset }}/{{ filebeat_configver }}/{{ beats_version.split(".")[0] }}/{{ item }}.j2'
    dest: '/etc/filebeat/{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - 'wazuh-template.json'
    - 'filebeat.yml'
  register: beats_config
