---
- name: Allow Beat service port
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ beats_port_arg | dict2items }}'
