---
- name: 'Add Beat {{ beats_version.split(".")[0] }} YUM repositories'
  yum_repository:
    name: '{{ beats_repo_name }}'
    description: '{{ beats_repo_name }} YUM repository'
    file: '{{ beats_repo_name }}'
    baseurl: '{{ beats_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Beat packages
  yum:
    name: '{{ beats_packages }}'
    state: 'present'
    enablerepo: '{{ beats_repo_name }}'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  register: beats_update
  until: beats_update is succeeded
  retries: 5
  delay: 2
