---
- name: 'Add Beats YUM repositories'.
  yum_repository:
    name: 'elasticsearch'
    description: 'Elasticsearch YUM repository'
    file: 'elasticsearch'
    baseurl: '{{ vars['beats_' + beats_dist + '_repo_url'] }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Beat packages.
  yum:
    name: '{{ beats_packages }}'
    state: 'present'
    enablerepo: 'elasticsearch'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  register: beats_update
  until: beats_update is succeeded
  retries: 5
  delay: 2